title:  MO-IT110 MotorPH Payroll System Documentation H2102 <br/>
subtitle: Arenal, I., Austria, JC., Olfato, S., Pascual, J. <br/>
#logo: /assets/img/logo.png
#description: Minimal is a theme for GitHub Pages.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
