title:  MO-IT110 MotorPH Payroll System Documentation H2102 <br/>
description: Arenal, I., Austria, JC., Olfato, S., Pascual, J. <br/>
#logo: /assets/img/logo.png
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
